#!/usr/bin/env bash 
#==========================================================================
export LC_TIME="C.UTF-8"
export LC_ALL="C.UTF-8" # useful on FreeBSD for making the tar work
export LANG="C.UTF-8"
#--------------------------------------------------------------------------
if [ "$MMMV_USERSPACE_DISTRO_T1_HOME" == "" ]; then
    MMMV_USERSPACE_DISTRO_T1_HOME="/home/mmmv/mmmv_userspace_distro_t1"
fi
#--------------------------------------------------------------------------
if [ ! -e "$HOME/.cargo" ]; then
    if [ ! -h "$HOME/.cargo" ]; then
        if [ -e "/home/mmmv/.cargo" ]; then
            if [ -d "/home/mmmv/.cargo" ]; then
                ln -s /home/mmmv/.cargo $HOME/.cargo
                sync; wait; sync;
            fi
        fi
    fi
fi
if [ -e "$HOME/.cargo/env" ]; then
    if [ ! -d "$HOME/.cargo/env" ]; then
        source "$HOME/.cargo/env"
    fi
fi
#--------------------------------------------------------------------------
#export DISPLAY=":0"
export MMMV_SB_DEBUG="t"  # domain: {"t","f"} 
MMMV_FP_COMMON_BASHRC_MAIN="$MMMV_USERSPACE_DISTRO_T1_HOME/mmmv/etc/common_bashrc/common_bashrc_main.bash"
if [ -e "$MMMV_FP_COMMON_BASHRC_MAIN" ]; then
    if [ ! -d "$MMMV_FP_COMMON_BASHRC_MAIN" ]; then
        alias mmmv_environment="nice -n 2 bash --rcfile \"$MMMV_FP_COMMON_BASHRC_MAIN\" "
    fi
fi
#--------------------------------------------------------------------------
# S_VERSION_OF_THIS_FILE="28060839-b1ce-4664-a129-4372c08196e7"
#==========================================================================
