#!/usr/bin/env bash
#==========================================================================

#--------------------------------------------------------------------------
if [ "$S_WHOAMI" == "mmmv" ]; then
    #----------------------------------------------------------------------
    S_TMP_0="$HOME/m_local/etc/list_of_vimwikis.txt"
    if [ "$SB_VIM_EXISTS_ON_PATH" == "t" ]; then
        alias mmmv_vim_edit_list_of_vimwikis="nice -n 2 vim $S_TMP_0 ; "
    fi
    if [ "$SB_RUBY_EXISTS_ON_PATH" == "t" ]; then
        alias mmmv_admin_update_list_of_vimwikis="mmmv_admin_vimwiki_list_of_wikis_2_vimrc_subpart_t1.rb '--origin=$S_TMP_0'"
    fi
    #----------------------------------------------------------------------
    S_TMP_0="/home/mmmv/mmmv_userspace_distro_t1/attic/documentation/application_specific_documentation/vimwiki/notes_set_01/in_vimwiki_format/index.wiki"
    if [ -e "$S_TMP_0" ]; then
        if [ ! -d "$S_TMP_0" ]; then
            alias mmmv_vimwiki_userspace_distro_t1_notes_set_01="vim $S_TMP_0 "
        fi
    fi
    #----------------------------------------------------------------------
    S_TMP_0="/home/mmmv/mmmv_userspace_distro_t1/attic/documentation/development_ideas/arendusideede_vimwiki/index.wiki"
    if [ -e "$S_TMP_0" ]; then
        if [ ! -d "$S_TMP_0" ]; then
            alias mmmv_vimwiki_userspace_distro_t1_development_ideas="vim $S_TMP_0 "
        fi
    fi
    #----------------------------------------------------------------------
fi
#==========================================================================
# S_VERSION_OF_THIS_FILE="4a645921-a659-4394-82d0-208230e0a7e7"
#==========================================================================
